<option value="12m">12 (Medical)</option>
<option value="11m">11 (Medical)</option>
<option value="12pe">12 (Pre-Engineering)</option>
<option value="11pe">11 (Pre-Engineering)</option>
<option value="12cs">12 (Computer Science)</option>
<option value="11cs">11 (Computer Science)</option>
<option value="10s">10 (Science)</option>
<option value="10a">10 (Arts)</option>
<option value="9s">9 (Science)</option>
<option value="9a">9 (Arts)</option>
<option value="8">8</option>
<option value="7">7</option>
<option value="6">6</option>
<option value="5">5</option>
<option value="4">4</option>
<option value="3">3</option>
<option value="2">2</option>
<option value="1">1</option>
<option value="playgroup">Playgroup</option>
<option value="nursery">Nursery</option>
<option value="prep">Prep</option>